# Generated by Django 5.0.7 on 2024-09-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_section_homework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
    ]
