# Generated by Django 5.0.7 on 2024-10-05 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_examcorrection'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcorrection',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='examcorrection',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
    ]
