# Generated by Django 5.0.7 on 2024-10-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_examcorrection_date_examcorrection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcorrection',
            name='material',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.material'),
        ),
    ]
