# Generated by Django 5.0.7 on 2024-10-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_examcorrection_section_examcorrection_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='examcorrection',
            name='margin1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examcorrection',
            name='margin2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examcorrection',
            name='margin3',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examcorrection',
            name='margin4',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='examcorrection',
            name='margin5',
            field=models.TextField(null=True),
        ),
    ]
