# Generated by Django 5.0.7 on 2024-10-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_examcorrection_margin1_examcorrection_margin2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examcorrection',
            name='margin1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examcorrection',
            name='margin2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examcorrection',
            name='margin3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examcorrection',
            name='margin4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examcorrection',
            name='margin5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
