# Generated by Django 5.0.7 on 2024-10-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_student_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lasstname',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentid',
            new_name='student_id',
        ),
    ]
