# Generated by Django 5.0.7 on 2024-10-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_rename_lasstname_student_lastname_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
