# Generated by Django 5.0.7 on 2024-10-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_delete_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
