# Generated by Django 5.0.7 on 2024-10-08 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_exammarks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExamMarks',
            new_name='ExamMark',
        ),
    ]
