# Generated by Django 5.0.7 on 2024-10-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_exam_exammark_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='massar_num',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
