# Generated by Django 5.0.7 on 2024-10-10 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_student_massar_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Material',
            new_name='Subject',
        ),
        migrations.AddField(
            model_name='exammark',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject'),
        ),
    ]
