# Generated by Django 5.0.7 on 2024-10-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_rename_material_subject_exammark_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammark',
            name='mark',
        ),
        migrations.AddField(
            model_name='exammark',
            name='first_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='second_mark',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exammark',
            name='third_mark',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
