# Generated by Django 5.0.7 on 2024-10-16 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_classe_students_remove_classe_name_classe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='home.section'),
        ),
        migrations.AlterField(
            model_name='classe',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='classe',
            name='students',
            field=models.ManyToManyField(related_name='classes', to='home.student'),
        ),
    ]
