# Generated by Django 5.0.7 on 2024-10-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_section_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='students', to='home.section'),
        ),
    ]
