# Generated by Django 5.0.7 on 2024-10-17 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_section_students_student_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='sections',
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='home.section'),
        ),
    ]
