# Generated by Django 5.0.7 on 2024-10-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_remove_student_sections_section_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.section'),
        ),
    ]
