# Generated by Django 5.0.7 on 2024-10-18 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_exammark_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.section'),
        ),
    ]
