# Generated by Django 5.0.7 on 2024-10-18 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_exammark_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='sections',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='home.section'),
        ),
    ]
