# Generated by Django 5.0.7 on 2024-10-18 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_section_students_student_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exammark',
            name='exam_name',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
