# Generated by Django 5.0.7 on 2024-10-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_remove_exammark_exam_name_delete_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='subjects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.subject'),
        ),
    ]
