# Generated by Django 5.0.7 on 2024-10-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_section_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='subjects',
        ),
        migrations.AddField(
            model_name='section',
            name='subjects',
            field=models.ManyToManyField(related_name='sections', to='home.subject'),
        ),
    ]
